### ISSUE TITLE
Where to upload gitian results?

### ISSUE THREAD

**Issue by laanwj** [magmaship/bip148org#3]
I've done a gitian build of tag "0.14.0-knotsbip148-rc1-INSECURE-TEST" and as far as I see it matches the SHA's on the page. Is there a repository similar to https://github.com/bitcoin-core/gitian.sigs for this project to upload signed assert files?

**Comment by magmaship** [comment]
@laanwj thank you :)

Created now:

https://github.com/magmaship/bitcoin-special-gitian.sigs

**Comment by magmaship** [comment]
CC: @da2ce7 @luke-jr

if still looking for Gitian confirmations of BIP148.

**Comment by laanwj** [comment]
https://github.com/magmaship/bitcoin-special-gitian.sigs/pull/1
